### ISSUE TITLE
single Rmd template and logo problem

### ISSUE THREAD

**Issue by dcossyleon** [rstudio4edu/rmd4edu#3]
@apreshill, I just realized that for someone who wants to use the rmd4edu template for a single Rmd page, it will not be self-evident (or even possible?) for them to change the placeholder "Your Logo Here" or footer.html by using the template alone.  

The [pimp my Rmd guy](https://github.com/holtzy/epuRate) was able to make the logo editable for a single page by defining a new YAML variable, but when I looked into how he did that I remember thinking that it was out of my wheelhouse (involved creating a [custom Pandoc template](https://bookdown.org/yihui/rmarkdown/template-pandoc.html)?).

So, my questions are:

1) Should we nix the logo for a single Rmd page?
or
2) Do you know how to make custom Pandoc templates?

**Comment by apreshill** [comment]
Did you use just straight up css? Wonder if we used code to specify image, then the css just styles that doc? Might not be as clean but would be more transparent perhaps: https://stackoverflow.com/questions/43009788/insert-a-logo-in-upper-right-corner-of-r-markdown-html-document

**Comment by dcossyleon** [comment]
Inline style tags for the win! The syntax looks a little weird with `logo` squeezed in between a string, but it works. I figured it was important for the image to be loaded with `knitr::image_uri()` instead of with a regular url in the CSS. Let me know if you have other ideas


```{r logo, echo = FALSE}

logo <- knitr::image_uri("logo-mark-rstudio4edu.png")

htmltools::withTags(
  style("#TOC::before {
          background-image: url(",logo,");
          margin-top: 50px;
        }")
)
```
![image](https://user-images.githubusercontent.com/29008894/62591960-64163a80-b89f-11e9-9722-07bccfc081ef.png)

**Comment by apreshill** [comment]
I think that is a GREAT solution, yay!
